# Generated by Django 4.2 on 2025-01-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About Item',
                'verbose_name_plural': 'About Items',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=255)),
                ('ios_url', models.URLField(db_index=True)),
                ('android_url', models.URLField(db_index=True)),
                ('ios_img', models.ImageField(upload_to='banner')),
                ('android_img', models.ImageField(upload_to='banner')),
                ('banner_img', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('delay', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_img', models.ImageField(upload_to='features')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_img', models.ImageField(upload_to='team')),
                ('member_full_name', models.CharField(max_length=255)),
                ('member_position', models.CharField(max_length=255)),
                ('delay', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_img', models.ImageField(upload_to='testimonials')),
                ('t_full_name', models.CharField(max_length=255)),
                ('t_role', models.CharField(max_length=255)),
                ('t_review', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WatchNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.URLField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(max_length=255)),
                ('delay', models.CharField(max_length=255)),
                ('central_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applight.featurescentral')),
            ],
        ),
    ]
